# BASE NODE
FROM node:16 AS base
WORKDIR /app
COPY package*.json ./

# DEPENDENCIES
FROM base AS dependencies
# Now install everything... that is needed for dev
RUN npm install && \
    npm install typescript && \
    npm install ts-node-dev

# DEVELOP
FROM dependencies AS develop
COPY . .
EXPOSE 80
CMD [ "npx", "ts-node-dev", "./src/index.ts" ]
