version: '3.9'
services:
  api:
    # container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-micro
    command: npm start
    volumes:
      - ./src:/app/src
    ports:
      - 3000:80

  test:
    # container_name: test
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-micro
    command: npm run watch:test
    volumes:
      - ./src:/app/src
